export const PRODUCTS = [
  {
    id: 'na1',
    name: 'nike running air max',
    title: 'nike running',
    subtitle: 'air max',
    price: 350,
    image: '/img/na1.png',
    section: 'arrival',
    category: 'sports',
    rating: 4.9,
  },
  {
    id: 'na2',
    name: 'nike running air gray',
    title: 'nike running',
    subtitle: 'air gray',
    price: 330,
    image: '/img/na2.png',
    section: 'arrival',
    category: 'sports',
    rating: 4.5,
  },
  {
    id: 'na3',
    name: 'nike running air basket',
    title: 'nike running',
    subtitle: 'air basket',
    price: 360,
    image: '/img/na3.png',
    section: 'arrival',
    category: 'sports',
    rating: 4.2,
  },
  {
    id: 'na4',
    name: 'addi running addidas',
    title: 'addi running',
    subtitle: 'addidas',
    price: 300,
    image: '/img/na4.png',
    section: 'arrival',
    category: 'sports',
    rating: 4.1,
  },
  {
    id: 'men1',
    name: 'nike men running',
    title: 'nike men running',
    subtitle: "men's collection",
    price: 300,
    image: '/img/men/men1.png',
    section: 'collection',
    category: 'men',
    rating: 4.1,
  },
  {
    id: 'sports1',
    name: 'nike sports running',
    title: 'nike sports running',
    subtitle: "sports collection",
    price: 300,
    image: '/img/sports/sports1.png',
    section: 'collection',
    category: 'sports',
    rating: 4.1,
  },
  {
    id: 'women1',
    name: 'nike women running',
    title: 'nike women running',
    subtitle: "women's collection",
    price: 300,
    image: '/img/women/women1.png',
    section: 'collection',
    category: 'women',
    rating: 4.1,
  },
  {
    id: 'men2',
    name: 'nike men sport',
    title: 'nike men sport',
    subtitle: "men's sport",
    price: 320,
    image: '/img/men/men2.png',
    section: 'collection',
    category: 'men',
    rating: 4.1,
  },
  {
    id: 'men3',
    name: 'nike men casual',
    title: 'nike men casual',
    subtitle: "men's casual",
    price: 280,
    image: '/img/men/men3.png',
    section: 'collection',
    category: 'men',
    rating: 4.1,
  },
  {
    id: 'women2',
    name: 'nike women sport',
    title: 'nike women sport',
    subtitle: "women's sport",
    price: 310,
    image: '/img/women/women2.png',
    section: 'collection',
    category: 'women',
    rating: 4.1,
  },
];

